definitions:
  domain.Article:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  request.CreateArticleRequest:
    properties:
      content:
        type: string
      title:
        type: string
      user_id:
        type: integer
    required:
    - content
    - title
    - user_id
    type: object
  response.Err:
    properties:
      error:
        description: user-facing error message
        type: string
      error_code:
        description: application-specific error code
        type: integer
    type: object
info:
  contact: {}
paths:
  /articles:
    get:
      parameters:
      - description: which page to load. Default to 1 if empty.
        in: query
        name: page
        type: integer
      - description: how many items per page. Default to 10 if empty.
        in: query
        name: per_page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Article'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Err'
      summary: List all articles
      tags:
      - articles
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Err'
      summary: Create an article
      tags:
      - articles
  /articles/{articleID}:
    get:
      parameters:
      - description: article ID
        in: path
        name: articleID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Article'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Err'
      summary: Get an article
      tags:
      - articles
  /articles/search:
    get:
      parameters:
      - description: search by title
        in: query
        name: title
        type: string
      - description: search by content
        in: query
        name: content
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Article'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Err'
      summary: Search articles
      tags:
      - articles
swagger: "2.0"
