version: "3.9"

name: "gab"

services:
  api:
    container_name: "chi-crud-gorm-api"
    image: yizeng/gab:chi-crud-gorm
    build:
      args:
        GO_VERSION: ${GO_VERSION}
      dockerfile: Dockerfile
      context: .
      target: development
    restart: always
    env_file: .env
    environment: # Overwrite some ENVs for Docker environment.
      - API_HOST=0.0.0.0
    volumes:
      - .:/project
    ports:
      - "${API_PORT}:${API_PORT}"
