# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: all tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  chi-gorm-auth-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "chi/gorm/auth-jwt"
          artifact_name: "chi-gorm-auth-jwt"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  chi-gorm-crud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "chi/gorm/crud"
          artifact_name: "chi-gorm-crud"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  chi-gorm-wip-complete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "chi/gorm/wip-complete"
          artifact_name: "chi-gorm-wip-complete"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  chi-minimum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "chi/minimum"
          artifact_name: "chi-minimum"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  gin-gorm-auth-jwt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "gin/gorm/auth-jwt"
          artifact_name: "gin-gorm-auth-jwt"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  gin-gorm-crud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "gin/gorm/crud"
          artifact_name: "gin-gorm-crud"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  gin-wip-complete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "gin/gorm/wip-complete"
          artifact_name: "gin-wip-complete"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  gin-minimum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests with coverage
        uses: "./.github/actions/test"
        with:
          working_directory: "gin/minimum"
          artifact_name: "gin-minimum"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          codecov_token: ${{ secrets.CODECOV_TOKEN }}